/**
 * Generated by karavan build tools - do NOT edit this file!
 */
import {v4 as uuidv4} from 'uuid';

export class Metadata {
    name: string = '';

    public constructor(init?: Partial<Metadata>) {
        Object.assign(this, init);
    }
}

export class Spec {
    flows?: any[] = [];
    dependencies?: string[] = [];

    public constructor(init?: Partial<Spec>) {
        Object.assign(this, init);
    }
}

export class Integration {
    apiVersion: string = 'camel.apache.org/v1';
    kind: string = 'Integration';
    metadata: Metadata = new Metadata();
    spec: Spec = new Spec();
    crd: boolean = true;

    public constructor(init?: Partial<Integration>) {
        Object.assign(this, init);
    }

    static createNew(name?: string): Integration {
        return new Integration({metadata: new Metadata({name: name}), spec: new Spec({flows: []})})
    }
}

export class CamelElement {
    uuid: string = ''
    dslName: string = ''

    constructor(dslName: string) {
        this.uuid = uuidv4()
        this.dslName = dslName
    }

    hasSteps(): boolean {
        return this.hasOwnProperty('steps');
    }

    hasStepName(): boolean {
        return this.hasOwnProperty('stepName');
    }
}

export class Beans extends CamelElement {
    beans: NamedBeanDefinition[] = []

    public constructor(init?: Partial<Beans>) {
        super("Beans")
        Object.assign(this, init);
    }
}

export class CamelElementMeta {
    step?: CamelElement
    parentUuid?: string
    position: number = 0;
    pathUuids: string [] = [];

    constructor(step?: CamelElement, parentUuid?: string, position?: number, pathUuids?: string []) {
        this.step = step;
        this.parentUuid = parentUuid;
        this.position = position || 0;
        this.pathUuids = pathUuids || this.pathUuids;
    }
}

