apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: amq
  application: amq
spec:
  acceptors:
    - port: 61616
      expose: true
      name: all
      protocols: all
      anycastPrefix: jms.queue.
      verifyHost: false
      sslEnabled: false
    - port: 1883
      expose: true
      name: mqtt
      protocols: mqtt
      anycastPrefix: jms.queue.
      verifyHost: false
      sslEnabled: false  
  adminPassword: admin
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    messageMigration: false
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder
  console:
    expose: true
  adminUser: admin

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: console
spec:
  to:
    kind: Service
    name: amq-hdls-svc
    weight: 100
  port:
    targetPort: console-jolokia
  wildcardPolicy: None
