apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karavan-data
spec:
  resources:
    requests:
      storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karavan-m2-cache
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karavan-jbang-cache
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem      
  accessModes:
    - ReadWriteOnce
   
