apiVersion: v1
kind: PersistentVolume
metadata:
  name: karavan-data
  labels:
    type: "karavanAmazonEbs"
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: volume-id
    