kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: karavan-image-puller-test
  namespace: karavan
subjects:
  - kind: ServiceAccount
    name: default
    namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'