# Service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  labels:
    app.kubernetes.io/name: pipeline
---
# Role deployer
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["*"]
  - apiGroups: ["", 'apps']
    resources: ["deployments", "services"]
    verbs: ["*"]
---
# Role bindings
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-deployer
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: karavan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer