apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: trait-example.yaml
spec:
  traits:
    camel:
      configuration:
        properties:
          - camel.component.seda.queueSize = 1
          - camel.component.seda.defaultPollTimeout = 5000
    environment:
      configuration:
        vars:
          - TEST_VARIABLE = HELLO_WORLD_
    logging:
      configuration:
        json: true
        level: DEBUG
  flows:
    - route:
        id: route1
        from:
          uri: timer:demo
          parameters:
            repeatCount: 10
          steps:
            - setBody:
                simple: '{{TEST_VARIABLE}}'
            - log:
                message: ${body}
                loggingLevel: INFO
            - to: seda:seda1
    - route:
        id: route2
        from:
          uri: seda:seda1
          parameters:
            size: 1
          steps:
            - log:
                message: ${body}
                loggingLevel: INFO    
