apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: postman.yaml
spec:
  flows:
    - rest:
        post:
          - to: direct:post
        path: /parcels
        consumes: application/json
        produces: application/json
    - route:
        from:
          uri: direct:post
          steps:
            - log:
                message: ${body}
            - multicast:
                steps:
                  - kamelet:
                      name: kafka-not-secured-sink
                      parameters:
                        topic: parcels
                        bootstrapServers: localhost:9092
                  - kamelet:
                      name: postgresql-sink
                      parameters:
                        serverName: localhost
                        serverPort: '5432'
                        username: postgres
                        password: postgres
                        databaseName: demo
                        query: >-
                          INSERT INTO parcels (id,address) VALUES
                          (:#id,:#address) ON CONFLICT (id)  DO NOTHING
                aggregationStrategy: >-
                  #class:org.apache.camel.processor.aggregate.UseOriginalAggregationStrategy
                parallelProcessing: false
                streaming: false
            - log:
                message: ${body}
        id: post
    - route:
        from:
          uri: kamelet:kafka-not-secured-source
          steps:
            - log:
                message: ${body}
          parameters:
            topic: parcels
            bootstrapServers: localhost:9092
