---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: karavan
    app.kubernetes.io/part-of: karavan
  name: karavan
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: karavan
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karavan
    app.openshift.io/runtime: camel
    app.kubernetes.io/part-of: karavan
  name: karavan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karavan
  template:
    metadata:
      labels:
        app: karavan
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: git-token
                  name: karavan
            - name: GIT_REPOSITORY
              valueFrom:
                secretKeyRef:
                  key: git-repository
                  name: karavan
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: git-username
                  name: karavan
          image: ghcr.io/apache/camel-karavan:0.0.16
          imagePullPolicy: Always
          name: karavan
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: karavan
    app.kubernetes.io/part-of: karavan
  name: karavan
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: karavan