kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: karavan-builder
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: karavan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'edit'