kind: Secret
apiVersion: v1
metadata:
  name: karavan
type: Opaque
stringData:
  master-username: admin
  master-password: karavan
  projects-git-repository: https://github.com/mgubaidullin/karavan-demo.git
  projects-git-password: demo
  projects-git-username: demo
  projects-git-main: main
  kamelets-git-repository: https://github.com/mgubaidullin/karavan-demo-kamelets.git
  kamelets-git-password: demo
  kamelets-git-username: demo
  kamelets-git-main: main
