apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: karavan-pipeline
spec:
  params:
    - name: PROJECT_NAME
      type: string
  tasks:
    - name: karavan-build-deploy
      params:
        - name: project
          value: $(params.PROJECT_NAME)
      taskRef:
        kind: Task
        name: karavan-builder
