apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: karavan-quarkus
spec:
  params:
    - name: PROJECT_NAME
      type: string
  tasks:
    - name: karavan-build-deploy
      params:
        - name: project
          value: $(params.PROJECT_NAME)
      taskRef:
        kind: Task
        name: karavan-quarkus-builder
      workspaces:
        - name: m2-cache
          workspace: m2-cache
        - name: jbang-cache
          workspace: jbang-cache  
  workspaces:
    - name: m2-cache
    - name: jbang-cache