---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: camel-karavan
    app.kubernetes.io/version: latest
  name: camel-karavan

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: camel-karavan
rules:
  - apiGroups: ["camel.apache.org"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: camel-karavan
  labels:
    app.kubernetes.io/name: camel-karavan
    app.kubernetes.io/version: latest
subjects:
  - kind: ServiceAccount
    name: camel-karavan
    namespace: default
roleRef:
  kind: ClusterRole
  name: camel-karavan
  apiGroup: rbac.authorization.k8s.io
