name: Feature request
description: Suggest an idea for this project
title: "Feature"
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      value: "A feature that simplifies the work of integration developers"
    validations:
      required: true
  - type: dropdown
    id: variant
    attributes:
      label: Variant
      description: To what Karavan variant this feature is related?
      options:
        - Web Application
        - VS Code Extension
        - Both
      default: 0
    validations:
      required: true
  - type: dropdown
    id: container
    attributes:
      label: Container Management (if applicable)
      description: What Container Management System are you running?
      options:
        - Docker
        - Kubernetes
        - Openshift
  - type: dropdown
    id: os
    attributes:
      label: Operating System (for VS Code Extension)
      options:
        - Linux
        - macOS
        - Windows
