apiVersion: gpte.opentlc.com/v1
kind: Gitea
metadata:
  name: gitea
spec:
  giteaImageTag: latest
  giteaSsl: false
  giteaAdminUser: administrator
  giteaAdminPassword: administrator
  giteaCreateUsers: true
  giteaGenerateUserFormat: karavan
  giteaUserNumber: 1
  giteaUserPassword: karavan
  giteaMigrateRepositories: true
  giteaRepositoriesList:
  - repo: https://github.com/mgubaidullin/karavan-demo-projects.git
    name: projects
    private: false
  - repo: https://github.com/mgubaidullin/karavan-demo-kamelets.git
    name: kamelets
    private: false