services:
  ${projectId}:
    hostname: "${projectId}-{{.Task.Slot}}"
    image: ${projectImage}
    restart: always
    ports:
      - "${projectPort}:8080"
    networks:
      - karavan
    deploy:
      restart_policy:
        condition: 'any'
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 250mb