apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
stringData:
  karavan.keycloak.url: {{ .Values.secret.keycloak.url | quote }}
  karavan.keycloak.realm: {{ .Values.secret.keycloak.realm | quote }}
  karavan.keycloak.frontend.clientId: {{ .Values.secret.keycloak.frontendClientId | quote }}
  karavan.keycloak.backend.clientId: {{ .Values.secret.keycloak.backendClientId | quote }}
  karavan.keycloak.backend.secret: {{ .Values.secret.keycloak.backendSecret | quote }}
  karavan.git.repository: {{ .Values.secret.git.repository | quote }}
  karavan.git.username: {{ .Values.secret.git.username | quote }}
  karavan.git.password: {{ .Values.secret.git.password | quote }}
  karavan.git.branch: {{ .Values.secret.git.branch | quote }}
  karavan.container-image.registry: {{ .Values.secret.containerImage.registry | quote }}
  karavan.container-image.group: {{ .Values.secret.containerImage.group | quote }}
  karavan.container-image.registry-username: {{ .Values.secret.containerImage.registryUsername | quote }}
  karavan.container-image.registry-password: {{ .Values.secret.containerImage.registryPassword | quote }} 