spec:
  replicas: 1
  template:
    spec:
      containers:
        - volumeMounts:
            - name: config
              mountPath: /app/config
        - env:
            - name: _JAVA_OPTIONS
              value: "-Duser.home=/tmp"
      serviceAccount: karavan