apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: default
data:
  app.ini: |
    APP_NAME = Gitea: Git with a cup of tea
    RUN_USER = git
    RUN_MODE = prod

    [repository]
    ROOT = /var/lib/gitea/git/repositories

    [repository.local]
    LOCAL_COPY_PATH = /tmp/gitea/local-repo

    [repository.upload]
    TEMP_PATH = /tmp/gitea/uploads

    [server]
    APP_DATA_PATH           = /var/lib/gitea
    SSH_DOMAIN              = localhost
    HTTP_PORT               = 3000
    ROOT_URL                = http://localhost:3000/
    DISABLE_SSH             = false
    ; In rootless gitea container only internal ssh server is supported
    START_SSH_SERVER        = true
    SSH_PORT                = 2222
    SSH_LISTEN_PORT         = 2222
    BUILTIN_SSH_SERVER_USER = git
    LFS_START_SERVER        = true
    LFS_CONTENT_PATH        = /var/lib/gitea/git/lfs
    DOMAIN                  = localhost
    LFS_JWT_SECRET          = xpgX8qpizPPfXuEO3swnmc_1mD4BQSdrUDr2XRr4T84
    OFFLINE_MODE            = false

    [database]
    PATH     = /var/lib/gitea/data/gitea.db
    DB_TYPE  = mysql
    HOST     = giteadb:3306
    NAME     = giteadb
    USER     = gitea
    PASSWD   = password
    SCHEMA   =
    SSL_MODE = disable
    CHARSET  = utf8
    LOG_SQL  = false

    [session]
    PROVIDER_CONFIG = /var/lib/gitea/data/sessions
    PROVIDER        = file

    [picture]
    AVATAR_UPLOAD_PATH            = /var/lib/gitea/data/avatars
    REPOSITORY_AVATAR_UPLOAD_PATH = /var/lib/gitea/data/gitea/repo-avatars
    DISABLE_GRAVATAR              = false
    ENABLE_FEDERATED_AVATAR       = true

    [attachment]
    PATH = /var/lib/gitea/data/attachments

    [log]
    ROOT_PATH = /var/lib/gitea/data/log
    MODE      = console
    LEVEL     = info
    ROUTER    = console

    [security]
    INSTALL_LOCK                  = true
    SECRET_KEY                    = FmgqWDkCFTpPmDlkrMVQRMtaKbLCc6IrianCSX6PHEHMNfxeLmoud6ggf3rBJQJj
    REVERSE_PROXY_LIMIT           = 1
    REVERSE_PROXY_TRUSTED_PROXIES = *
    INTERNAL_TOKEN                = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2MzE5NzUwNDF9.MXbNy42KnjCGtDM2j4TdF7X-cVAgfPq6sh__-W2nCFo
    PASSWORD_HASH_ALGO            = pbkdf2

    [service]
    DISABLE_REGISTRATION              = false
    REQUIRE_SIGNIN_VIEW               = false
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = false
    DEFAULT_ENABLE_TIMETRACKING       = false
    NO_REPLY_ADDRESS                  =

    [oauth2]
    JWT_SECRET = m_zVtzGY5X_YIOa7AMHpSAJxjiMyorz6JQFbgqm8-Tg

    [mailer]
    ENABLED = false

    [openid]
    ENABLE_OPENID_SIGNIN = false
    ENABLE_OPENID_SIGNUP = false