apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: karavan
    openshift.io/display-name: karavan
  name: karavan
spec:
  finalizers:
    - kubernetes

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: karavan-demo
    openshift.io/display-name: karavan-demo
  labels:
    argocd.argoproj.io/managed-by: karavan
  name: karavan-demo
spec:
  finalizers:
    - kubernetes