version: '3.8'

services:

  gitea:
    image: gitea/gitea:1.20.2-rootless
    restart: always
    ports:
      - "3000:3000"

  registry:
    image: registry:2
    restart: always
    ports:
      - "5555:5000"