version: '3.8'

services:

  infinispan:
    image: quay.io/infinispan/server:14.0.21.Final
    restart: always
    ports:
      - "11222:11222"

  gitea:
    image: gitea/gitea:1.20.2-rootless
    restart: always
    ports:
      - "3000:3000"

  registry:
    image: registry:2
    restart: always
    ports:
      - "5555:5000"