apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: camel-k
  namespace: openshift-operators
spec:
  channel: stable-1.6
  installPlanApproval: Automatic
  name: camel-k
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: camel-k-operator.v1.6.0