name: Karavan Devmode

on:
  push:
    branches: [ main ]
    paths: ['karavan-devmode/Dockerfile', '.github/workflows/docker-devmode.yml']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-devmode
  TAG: 4.22.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Note: actions/checkout only goes up to v4 currently

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/camel
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build Karavan DevMode Application
        working-directory: ./karavan/karavan-devmode
        run: mvn clean package

      - name: Set up QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
        
      - name: Set up Docker Buildx
        run: |
          docker buildx create --use

      - name: Log in to the Container registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build and push Devmode image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file ./karavan/karavan-devmode/Dockerfile \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            --push \
            --no-cache \
            --sbom=true \
            --provenance=mode=max \
            ./karavan/karavan-devmode