name: Installer

on:
  push:
    branches: [ main ]
    paths: ['karavan-web/karavan-installer/**', '.github/workflows/installer.yml']
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  TAG: 4.1.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Karavan
        uses: actions/checkout@v3
        with:
          path: karavan

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/camel/karavan
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      
      #  Build Karavan installer
      - name: Build Karavan installer
        working-directory: ./karavan/karavan-web/karavan-installer
        run: |
          mvn package
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Karavan installer (upload)
        uses: actions/upload-artifact@v3
        with:
          name: karavan-installer.jar
          path: ./karavan/karavan-web/karavan-installer/target/karavan-installer-${{ env.TAG }}.jar
        if: ${{ github.ref == 'refs/heads/main' }}