apiVersion: "v1"
kind: "Service"
metadata:
  name: "karavan"
spec:
  ports:
  - name: "http"
    nodePort: 30777
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: "karavan"
  type: "NodePort"