---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "karavan-role-binding"
roleRef:
  kind: "Role"
  apiGroup: "rbac.authorization.k8s.io"
  name: "karavan"
subjects:
- kind: "ServiceAccount"
  apiGroup: ""
  name: "karavan"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "karavan-cluster-role-binding"
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: "view"
subjects:
- kind: "ServiceAccount"
  apiGroup: ""
  name: "karavan"