---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "karavan"
stringData:
  karavan.keycloak.url: "https://localhost"
  karavan.keycloak.realm: "karavan"
  karavan.keycloak.frontend.clientId: "karavan"
  karavan.keycloak.backend.clientId: "karavan"
  karavan.keycloak.backend.secret: "secret"
  karavan.git.repository: "http://reporitory/karavan/karavan.git"
  karavan.git.username: "karavan"
  karavan.git.password: "karavan"
  karavan.git.branch: "main"
  karavan.container-image.registry: "registry:5000"
  karavan.container-image.group: "karavan"
  karavan.container-image.registry-username: 
  karavan.container-image.registry-password:
